@Library("jenkins-library@main")

import com.logicalclocks.jenkins.k8s.ImageBuilder


node("local") {
    stage('Clone repository') {
      checkout scm
    }

    stage('Build and push image(s)') {
      withCredentials([usernamePassword(credentialsId: 'a0770738-4ef3-4acc-a6ba-097ee6c85b44', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
        sh """
              mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev 'Download|INFO|WARNING' > version.log
              export VERSION=\$(cat version.log)
              echo -n \$VERSION > version.log
              echo \$VERSION

              mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=image.build.version | grep -Ev 'Download|INFO|WARNING' > build_version.log
              export BUILD_VERSION=\$(cat build_version.log)
              echo -n \$BUILD_VERSION > build_version.log
              echo \$BUILD_VERSION
        """
        version = readFile("${env.WORKSPACE}/version.log").trim()
        buildVersion = readFile("${env.WORKSPACE}/build_version.log").trim()
        withEnv(["HIVE_VERSION=${version.trim()}", "IMAGE_BUILD_VERSION=${buildVersion.trim()}"]) {
          def builder = new ImageBuilder(this)

          sh """
            cat > $WORKSPACE/mvn-settings.xml << EOF
<settings>
  <servers>
    <server>
      <id>HopsEE</id>
      <username>$USERNAME</username>
      <password>$PASSWORD</password>
    </server>
  </servers>
</settings>
EOF
            mvn dependency:copy \
              -s $WORKSPACE/mvn-settings.xml \
              -Dartifact=io.hops.hive:hive-packaging:\${HIVE_VERSION}:tar.gz:bin \
              -DoutputDirectory=$WORKSPACE/dockerfiles/ \
              -Dmdep.stripVersion=true \
              -U
            mv $WORKSPACE/dockerfiles/hive-packaging-bin.tar.gz $WORKSPACE/dockerfiles/hive-packaging-\${HIVE_VERSION}-bin.tar.gz
            rm $WORKSPACE/mvn-settings.xml
          """
          sh "printf \"user=$USERNAME\npassword=$PASSWORD\" > $WORKSPACE/dockerfiles/wgetrc"
          sh "ls $WORKSPACE/dockerfiles"

          m = readFile "${env.WORKSPACE}/dockerfiles/build-manifest.json"
          builder.run(m)
        }
      }
    }
}
